conf/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django_js_reverse.views import urls_js


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^jsreverse/$', urls_js, name='js_reverse'),
]

tasks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^change-state/(?P<id>\w+)/$', views.change_state, name='change_state'),
    url(r'^delete/(?P<id>\w+)/$', views.delete, name='delete'),
]

tasks/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=120)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name', )

tasks/views.py
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render

from .forms import TaskForm
from .models import Task


def index(request):
    if request.method == 'POST' and request.is_ajax():
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse(model_to_dict(form.instance))
    else:
        form = TaskForm()
    return render(request, 'tasks/index.html', {'tasks': Task.objects.all(), 'form': form})


def change_state(request, id):
    task = Task.objects.get(pk=id)
    task.completed = not task.completed
    task.save()

    return JsonResponse({'taskCompleted': task.completed})


def delete(request, id):
    task = Task.objects.get(pk=id)
    task.delete()
    return JsonResponse({'response': 'ok'})

tasks/templates/tasks/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>.completed { text-decoration: line-through; }</style>
</head>
<body>
    <h2>Tasks</h2>

    <ul class="list-group">
        {% for task in tasks %}
            <li class="list-group-item">
                <a href="{% url 'tasks:change_state' task.id %}"
                    class="task {% if task.completed %}completed{% endif %}"
                    onclick='changeState(event, $(this))'>
                    {{ task }}
                </a>
                <a href="{% url 'tasks:delete' task.id %}" onclick='deleteTask(event, $(this))'>x</a>
            </li>
        {% endfor %}
    </ul>

    <form method="post" onsubmit='createTask (event, $(this))'>
        {% csrf_token %}
        {{ form.name }}
        <button type="submit">create</button>
    </form>

    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>